run_name: example_run
start_date: 2023.01.01  # in this format 2023.01.01
end_date: 2024.01.01 # int this format 2023.12.31
period: D1 # Chart time period
main_chart_symbol: EURUSD
currency: USD
deposit: 100000
leverage: 100
data_split: month # Options: none, year, month
risk: 2 # Risk in percent (used in lot size calculation)
sl: 1.5  # Stop loss s
tp: 1 # Take profit

opt_settings:
  Trigger:
    opt_criterion: 6
    custom_criterion: 1
    min_trade: 100
    max_iterations: 100

  Conformation:
    opt_criterion: 6
    custom_criterion: 1
    min_trade: 200
    max_iterations: 100

  Trendline:
    opt_criterion: 5
    custom_criterion: 99
    min_trade: 0
    max_iterations: 100

  Volume:
    opt_criterion: 6
    custom_criterion: 1
    min_trade: 20
    max_iterations: 100

  Exit:
    opt_criterion: 6
    custom_criterion: 1
    min_trade: 30
    max_iterations: 100
