run_name: example_run
pipeline: trend_following
whitelist_file: whitelist.yaml # CHART_SYMBOL_ONLY
start_date: 2023.01.01
end_date: 2024.01.01
period: D1
main_chart_symbol: EURUSD
currency: USD
deposit: 100000
leverage: 100
data_split: month
risk: 2
sl: 1.5
tp: 1

opt_settings:

  Trigger:
    opt_criterion: 6
    custom_criterion: 1
    min_trade: 100
    max_iterations: 100

  Conformation:
    opt_criterion: 6
    custom_criterion: 1
    min_trade: 20
    max_iterations: 100

  Trendline:
    opt_criterion: 5
    custom_criterion: 99
    min_trade: 0
    max_iterations: 100

  Volume:
    opt_criterion: 6
    custom_criterion: 1
    min_trade: 20
    max_iterations: 100

  Exit:
    opt_criterion: 6
    custom_criterion: 1
    min_trade: 30
    max_iterations: 100
